apiVersion: v1alpha
kind: playwright
sauce:
  region: eu-central-1
  # This tells saucectl to use your active tunnel
  tunnel:
    name: "my-local-test-tunnel"
playwright:
  version: 1.52.0 # Using the version from your package.json
  configFile: playwright.config.js
rootDir: ./
suites:
  - name: "Localhost Test - Chrome on Mac"
    platformName: "macOS 12"
    # This line tells Playwright to ONLY run the example.spec.js file
    testMatch: ["tests/example.spec.js"]
    # 'params' is a required field.
    # 'project' must be nested inside 'params'.
    params:
      browserName: "chromium"
      project: "chromium"
